### ISSUE TITLE
Implement a keyed alphabet generator

### ISSUE THREAD

**Issue by dex-r** [arosspope/cipher-crypt#12]
I think it will be useful to have a "common" function to generate a scrambled alphabet from a key. e.g. for a key of `alphabet` you would get an alphabet of `alphbetcdfgijkmnoqrsuvwxyz`. This could be used with several of the ciphers in the README.

**Comment by dex-r** [comment]
Implemented in PR #13

**Comment by arosspope** [comment]
I agree that this would be useful, but I think it should be implemented when we actually tackle one of the ciphers that would use it. Thanks
