### ISSUE TITLE
Implement Fractionated Morse cipher

### ISSUE THREAD

**Issue by dex-r** [arosspope/cipher-crypt#14]
I was thinking of implementing this. Two things: 

- Having a file/struct name like `FractionatedMorse` seems a bit long. Would something like `FracMorse` be preferable or should i spell it out in full.
- Should I include encoding of numbers? It would mean a new alphabet and a new set of access functions.

**Comment by arosspope** [comment]
1. I think we should keep the full name to make it clear, unless you can provide evidence/examples if its ever referenced to in abbreviated way.
2. If encoding of numbers is something we need for a cipher, then yes I would include a new alphabet and access functions. I would prefer the original functions to remain unmodified if this happens to ensure simplicity.

**Comment by dex-r** [comment]
For the new alphabets I was thinking a new common file called `alphanumerics.rs`, with the same functions as in `alphabet.rs`, namely `find_position` and `get_letter`. Alternatively I could put new functions in `alphabet.rs` named `find_alphanumeric_position` and `get_alphanumeric_symbol`. Which do you reckon?

**Comment by arosspope** [comment]
I think we should keep it collated in the one file if possible. We can review the naming of the acess methods when we do the PR 😊

**Comment by arosspope** [comment]
See PR #18
