### ISSUE TITLE
Implement ADFGVX Cipher

### ISSUE THREAD

**Issue by arosspope** [arosspope/cipher-crypt#25]

**Comment by avastmick** [comment]
Happy to take this on. I was mindlessly re-doing what you've already done before I _actually_ looked properly...

I was looking to port over [picipher](https://github.com/jameslyons/pycipher) to Rust and had made some progress, I've dumped that now as it is just repeating what you've already done.

I've run your code through `rustfmt` and `clippy`and I'll also look to check coverage etc. before I PR.

Cheers

**Comment by arosspope** [comment]
Hey there, thanks for the input. I'll assign this issue to you if you don't mind. 😊

**Comment by avastmick** [comment]
That's great.

**Comment by arosspope** [comment]
Looks like I can't assign you from my end. If you don't mind, could you create a new issue detailing the changes you are making (ADFGVX, integrating rustfmt, etc.)?

**Comment by avastmick** [comment]
Okay - I'll do that in the incoming PR, and raise an issue on some of the integration issues that have come out of the implementation.

I *think* you can only assign someone to an issue if they are formally included as `collaborators`... I wouldn't bother. Have a look at the PR and see what you think.

**Comment by avastmick** [comment]
See PR #29
